Build process change: building out of source. Since there was so much pressure recently, I have modified the build scripts to allow building of the model outside of source tree (i.e. putting .o and .mod to different directories, separate for each rundeck).
I did it in a rather rough way at the moment, so it is possible
that something will not work as expected. Use at your own risk
and let me know if you see problems. I'll clean it up later,
when I have time.

Those who don't want this functionality can stop reading now.
The default behaviour of the build system didn't change. But let
me know if you think that something got broken.

To enable this functionality specify BUILD_OUT_OF_SOURCE=YES
on a compile line (and with all other related "make" commands)
or add it to your ~/.modelErc .

Once it is enabled, "make setup ..." will create a directory
<run_id>_obj in decks directory and store all .o and .mod files
under this directory (separately for each rundeck). When doing
"make clean" make sure to specify rundeck name with RUN=... ,
so that make knows which directory to clean, or just delete
the corresponding *_obj directory.

If you want to work completely separately from the source directory
tree (for example, on a different file system), do the following.

1. create a directory where you want to work (this will be a remote
equivalent of "decks" directory).
2. symlink modelE/decks/Makefile to this directory
3. set an environment variable MODEL_E_ROOT to the location of
your modelE directory with the source code
4. work as described above (with BUILD_OUT_OF_SOURCE=YES set).
Build files (.o, .mod) will be stored under <run_id>_obj in
your working directory.

There is one exception to this "build out of source" rule:
Fortran files produced by the call to m4 are still stored inside
the source tree, since they have to be eventually committed to
the repository.

You may want to know, that makefiles are copied to build tree
only once (when one does the first setup). So if you modify
a makefile in the source tree, you may want to delete the build
directory to force it to get rebuild (simple "make clean" will
not do it).

diff --git a/decks/Makefile b/decks/Makefile
--- a/decks/Makefile
+++ b/decks/Makefile
@@ -2,8 +2,13 @@
 .PHONY: force rundeck depend gcm setup clean vclean newstart exe cmp .R htmldoc setup_script setup_nocomp tests check_vars
 
 # modelE directory structure
-MODEL_E_ROOT = ..
-MODEL_DIR = $(MODEL_E_ROOT)/model
+MODEL_E_ROOT ?= $(shell pwd)/..
+ifeq ($(BUILD_OUT_OF_SOURCE),YES)
+  MODEL_E_BUILD_DIR = $(RUN)_obj
+else
+  MODEL_E_BUILD_DIR = $(MODEL_E_ROOT)
+endif
+MODEL_DIR = $(MODEL_E_BUILD_DIR)/model
 AUX_DIR = $(MODEL_E_ROOT)/aux
 SCRIPTS_DIR = $(MODEL_E_ROOT)/exec
 DECKS_DIR = $(shell pwd)
@@ -46,6 +51,11 @@ export NETCDFHOME
 # For unit tests
 export F90FLAGS
 export CPPFLAGS
+
+# export for build process
+export MODEL_E_ROOT
+export CONFIG_DIR
+export SCRIPTS_DIR
 
 V =
 
@@ -97,9 +107,16 @@ rundeck: linkNonProduction
 	@echo '### Information below describes your run. Do not delete! ###'\
 	    >> $(DECKS_REPOSITORY)/$(RUN).R
 
-depend: $(RUN).mk
+depend: $(RUN).mk $(MODEL_DIR)/Makefile
 	$(MAKE) check_sanity RUN=$(RUN)
 	$(MAKE) -C $(MODEL_DIR) depend_all RUN=$(RUN) DECKS_DIR=$(DECKS_DIR) $(OPTS_MAIN)
+
+ifeq ($(BUILD_OUT_OF_SOURCE),YES)
+$(MODEL_DIR)/Makefile: $(MODEL_E_ROOT)/model/Makefile
+	if [ ! -d $(MODEL_E_BUILD_DIR) ] ; then  mkdir $(MODEL_E_BUILD_DIR) ; fi
+	if [ ! -d $(MODEL_DIR) ] ; then  mkdir $(MODEL_DIR) ; fi
+	cp $(MODEL_E_ROOT)/model/Makefile $(MODEL_DIR)/Makefile
+endif
 
 
 gcm $(BIN_DIR)/$(RUN).exe: $(RUN).mk $(BIN_DIR) depend check_vars
@@ -219,6 +236,10 @@ auxqflux: aux
 auxdeep: aux
 	$(MAKE) odeep -C $(AUX_DIR) RUN=$(RUN) DECKS_DIR=$(DECKS_DIR) $(OPTS_MAIN)
 
+ifeq ($(BUILD_OUT_OF_SOURCE),YES)
+clean: check_RUN
+endif
+
 clean vclean clean_all:
 	$(MAKE) -C $(MODEL_DIR) $@ $(OPTS_MAIN)
 ifneq ($(PFUNIT),)
@@ -320,7 +341,7 @@ src_cpp_dir:
 etags:
 	$(MAKE) -C $(MODEL_DIR) $@ RUN=$(RUN) DECKS_DIR=$(DECKS_DIR) $(OPTS_MAIN)
 
-$(RUN).mk: $(RUN).R $(SCRIPTS_DIR)/r_to_mk.pl
+$(RUN).mk: $(DECKS_DIR)/$(RUN).R $(SCRIPTS_DIR)/r_to_mk.pl
 	@if [ -z "$(RUN)" ]; then echo "Please specify RUN name"; exit 1; fi
 	$(SCRIPTS_DIR)/r_to_mk.pl $< > $@
 
@@ -339,6 +360,12 @@ check_sanity:
 	@if [ "$(COMPONENTS)"xx = xx ] ; then \
 	  echo "Your rundeck contains no Components" ; \
 	  echo "Old style rundeck ?  ... aborting ..." ; \
+	  exit 1 ; fi
+
+check_RUN:
+	@if [ "$(RUN)"xx = xx ] ; then \
+	  echo "Your have to specify rundeck name with RUN=..." ; \
+	  echo "... aborting ..." ; \
 	  exit 1 ; fi
 
 check_vars:
